### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by WinXaito** [firm1/zest-writer#59]
Il serait bien que quand nous cliquons sur un bouton (Gras, italique, etc.) le focus soit garder dans la zone d'édition.

**Comment by firm1** [comment]
Bonne idee

**Comment by WinXaito** [comment]
Je prend

**Comment by WinXaito** [comment]
Tu pourrais m'aider ? Je ne comprend pas du tout le dernier message [RichTextFX](https://github.com/TomasMikula/RichTextFX/issues/293#issuecomment-213079640)

**Comment by firm1** [comment]
En fait il voudrait que tu leur montre un exemple simple de code qui
explique le probleme. Ils n'ont pas envie de compiler ZestWriter pour
comprendre ton problème.

Mais je peux regarder aussi, mais pas tout de suite (pas encore @home)

**Comment by WinXaito** [comment]
Yep, de toute façon il est l'heure pour moi d'aller me coucher.

Si tu as le moment d'y jeter un coup d’œil c'est volontiers (Car je ne sais même pas s'il comprenne mes google translate à l'arrache).

**Comment by JordanMartinez** [comment]
(Traduire avec Google) Bonjour messieurs. Je suis désolé que je ne parle pas français. Cependant, tout ce que vous devez faire est d'ajouter la ligne de code suivante pour résoudre votre problème:
```` Java
@FXML private void HandleBoldButtonAction(ActionEvent event) {
    SourceText.replaceText(SourceText.getSelection(), "**" + SourceText.getSelectedText() + "**");

    SourceText.requestFocus();
    SourceText.positionCaret(0); // Où l'indice est partout où vous voulez que le caret
}
````


**Original**:

Hello gentlemen. I'm sorry that I don't speak French. However, all you need to do is add the following line of code to fix your problem:
````java
@FXML private void HandleBoldButtonAction(ActionEvent event) {
    SourceText.replaceText(SourceText.getSelection(), "**" + SourceText.getSelectedText() + "**");

    SourceText.requestFocus();
    SourceText.positionCaret(0); // where index is wherever you want the caret
}
````

**Comment by JordanMartinez** [comment]
Le caret de `StyledTextArea` apparaît uniquement visible lorsque les 3 conditions sont remplies:
- La région se concentre
- La zone est modifiable
- La zone n'a pas été désactivée

Étant donné que vous cliquez sur un bouton, il supprime l'accent de la région. Donc, vous êtes en effet mettez à jour le caret, mais il ne sera pas apparaître visiblement jusqu'à ce que vous appelez aussi `StyledTextArea#requestFocus`.

**Original:**

`StyledTextArea`'s caret only visibly appears when all 3 conditions are met:
- the area is focused
- the area is editable
- the area is not disabled

Since you click on a button, it removes the area's focus. So, you are indeed updating the caret, but it won't appear visibly until you also call `StyledTextArea#requestFocus`.

**Comment by JordanMartinez** [comment]
Mes excuses. Je suis parti le mal commis. Je vois maintenant le problème que vous avez rencontré.

Je l'ai expliqué le problème dans le numéro RichTextFX

**Original:**

My apologies. I checked out the wrong commit. I now see the problem you have encountered.

I've explained the problem in the RichTextFX issue

**Comment by JordanMartinez** [comment]
Au lieu de `positionCaret(0)`, utilisez `moveTo(0)`. Cela résout le problème.

Le crédit va à: Tomas Mikula

**Original:**

Instead of `positionCaret(0)`, use `moveTo(0)`. This fixes the issue.

Credit: Tomas Mikula

**Comment by firm1** [comment]
Great thanks @JordanMartinez for your advices. It's a pleasure working with devs like you.

@WinXaito je crois qu'il t'as donné la solution là.

**Comment by JordanMartinez** [comment]
@firm1 You're welcome. All the best to you and your team and this project's goals.

**Comment by WinXaito** [comment]
Thanks !

**Comment by firm1** [comment]
Problème corrigé.
